---
title: "Section 3.3 Treatment and treatment coverage"
author: "Hazim Timimi"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
      out_dir <- "./html_drafts";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})
output: 
  html_fragment:
    # Don’t include a table of contents
    toc: no
    # Set standard figure width to 12 inches
    fig_width: 12
    # Don’t write figure captions
    fig_caption: FALSE
    # to save intermediate .png
    keep_md: true
    # Don't embed external resources (stylesheets, JS libraries) in the output 
    self_contained: FALSE
# To run this file and store output as html:
# rmarkdown::render(here::here("report/ch3-3.rmd"), output_file = "ch3-3.html", output_dir = here::here("report/html_drafts/"))
---


```{r setup, include=FALSE}
# Set chunk options.
# Results "asis" is useful to output markdown from a function
# Suppress messages, warnings and also the ## at the beginning of printed text

knitr::opts_chunk$set(echo = FALSE, 
                      results = "asis",
                      message = FALSE,
                      warning = FALSE,
                      error = TRUE)  # TEMP error=TRUE for debugging!

# Kill any attempt at using factors, unless we explicitly want them!
options(stringsAsFactors=FALSE)

# Load output packages ----
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
library(gtbreport)

library(jsonlite)
library(dplyr)
library(here)

# Get the data sets and computed values/statistics for section 3.3 ----
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
source(here('report/ch3-3_prepare_data.r'))

```


```{css, echo=FALSE}

/* Styles to make it easier to see in the html_fragment; this CSS can be included in the CSS widget of Sitefinity */
  

.red, .red a {
  color: #F21905; /* red text to show figure number */
}



```

<!-- Add links to stylesheets, JQuery and Kendo UI  -->

<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.301/styles/kendo.common.min.css" />
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.301/styles/kendo.default.min.css" />
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.301/styles/kendo.default.mobile.min.css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<script src="https://kendo.cdn.telerik.com/2022.1.301/js/jquery.min.js"></script>
<script src="https://kendo.cdn.telerik.com/2022.1.301/js/kendo.all.min.js"></script>
<script src="https://docs.telerik.com/kendo-ui/assets/bootstrap.min.js"></script>
<!-- End of links section -->



# 3.3 TB treatment and treatment coverage    


_Draft! Prepared `r Sys.Date()` using country-reported data CSV files dated `r csv_datestamp` `r if(show_estimates){paste0('and estimates files dated ', csv_estimate_datestamp)}`_


### <span class="red">Fig. 3.3.1</span> Estimated TB treatment coverage^a^ in `r report_year-1`, 30 high TB burden countries^b^, WHO regions and globally

<div id="fig_3_3_1"></div>


### <span class="red">Fig. 3.3.2</span> Estimated TB treatment coverage^a^ among children aged 0&#8211;14 years and adults aged ≥15 years in `r report_year-1`, 30 high TB burden countries,^b^ WHO regions and globally

<div class="row">
<div class="col-md-6">
<div id="fig_3_3_2a"></div>
</div>
<div class="col-md-6">
<div id="fig_3_3_2b"></div>
</div>
</div>


### <span class="red">Fig. 3.3.3</span> The ten countries with the largest gaps between notifications of people with a new or relapse episode of TB (incident cases) and the best estimates of TB incidence, `r report_year-1`^a,b^

<span class="red">**!static figure!**</span>


### <span class="red">Fig. 3.3.4</span> Estimated global number of incident cases of TB among people living with HIV<span style="color:`r gtbreport::palette_gtb("inch")`;"> (red)</span> compared with the global number of people notified with a new or relapse episode of TB who were known to be HIV-positive (black) and the global number of TB patients who were started on antiretroviral therapy<span style="color:#277abe;"> (blue)</span>, 2004&#8211;`r report_year-1`  


<div id="fig_3_3_4"></div>


### <span class="red">Fig. 3.3.5</span> Estimated coverage of antiretroviral therapy for people living with HIV who developed TB^a^ in `r report_year-1`, 30 high TB/HIV burden countries,^b^ WHO regions and globally


<div id="fig_3_3_5"></div>


### <span class="red">Fig. 3.3.6</span> Treatment outcomes for people diagnosed with a new or relapse episode of TB in `r report_year-2`, WHO regions and globally  

<div id="fig_3_3_6"></div>



### <span class="red">Fig. 3.3.7</span> Treatment outcomes for people diagnosed with a new or relapse episode of TB globally 2012&#8211;`r report_year-2` 

<div id="fig_3_3_7a"></div>
<div id="fig_3_3_7b"></div>


### <span class="red">Fig. 3.3.8</span> Treatment outcomes for people living with HIV who were diagnosed with a new or relapse episode of TB in `r report_year-2`, WHO regions and globally  

<div id="fig_3_3_8"></div>



### <span class="red">Fig. 3.3.9</span> Treatment success rates for children aged 0&#8211;14 years who were diagnosed with a new or relapse episode of TB in `r report_year-2`, WHO regions and globally^a^ 

<div id="fig_3_3_9"></div>



### <span class="red">Table 3.3.1</span> Cumulative number of deaths averted by TB and TB/HIV interventions 2000&#8211;`r report_year - 1` (in millions), globally and by WHO region

<span class="red">**!static figure!**</span>



<script type="text/javascript">
/* JSON data objects for the figures */

var fig_3_3_1_data = `r f3.3.1_data %>% mutate(value = c_cdr, lo = c_cdr_lo, hi = c_cdr_hi) %>% toJSON("rows")`   ;  

var fig_3_3_2a_data = `r f3.3.2a_data %>% toJSON("rows")`   ;  

var fig_3_3_2b_data = `r f3.3.2b_data %>% toJSON("rows")`   ;  

var fig_3_3_4_data = `r f3.3.4_data %>% toJSON("rows")`   ;  

var fig_3_3_5_data = `r f3.3.5_data %>% mutate(value = c_art, lo = c_art_lo, hi = c_art_hi) %>% toJSON("rows")`   ;  

var fig_3_3_6_data = `r f3.3.6_data %>% pivot_wider(names_from = outcome, values_from = value) %>% rename(succ=2, fail=3, died=4, ltfu=5, neval=6) %>% toJSON("rows")` ;

var fig_3_3_7_data = `r f3.3.7_data %>% pivot_wider(names_from = outcome, values_from = value) %>% rename(succ=3, fail=4, died=5, ltfu=6, neval=7) %>% arrange(rev(year)) %>% toJSON("rows")` ;

var fig_3_3_8_data = `r f3.3.8_data %>% pivot_wider(names_from = outcome, values_from = value) %>% rename(succ=2, fail=3, died=4, ltfu=5, neval=6) %>% toJSON("rows")` ;

var fig_3_3_9_data = `r f3.3.9_data  %>% toJSON("rows")` ;

</script>

  
```{js, echo=FALSE}

/* Functions to create the figures */

/* Functions to organize number with thousands separator */
function num_spacer(number) {
  // Change thousands separator to a non-breaking space as per WHO standard
      if (number >= 10 | number==0) {
        return kendo.toString(number, 'n0').replace(/,/g, '&nbsp;');
      } else if (number<10 & number>=1) {
      return kendo.toString(number, 'n1').replace(/,/g, '&nbsp;');
      } else {
      return kendo.toString(number, 'n2').replace(/,/g, '&nbsp;');
      }
}

function axis_spacer(number) {
  // Change thousands separator to a non-breaking space as per WHO standard
      if (number >= 10 | number == 0 ) {
        return kendo.toString(number, 'n0').replace(/,/g, ' ');
      } else {return kendo.toString(number, 'n1').replace(/,/g, ' ');
             }
}

/* format a number as thousands using GTB rounding rules */
function tb_format_thou(n) { 
  nt = n/1000; 
  if (nt < 100) {
    ntform = Number(nt.toPrecision(2))*1000;
      } else {
    ntform = Number(nt.toPrecision(3))*1000;
  } 
  return num_spacer(ntform)
}

function tb_format_pct(n) { 
  // Show percentages to 2 sig figs if under 100%
  if (n < 99.5) {
    return Number(n.toPrecision(2))
      } else {
    return Number(n.toPrecision(3))
  } 
}

function createFig_3_3_1(fig_ID, data, color) {
   
		$(fig_ID).kendoChart({
			dataSource: data,
			chartArea: {
				height: 900
			},	
			legend: {
				position: "bottom"
			},
			series: [{
        type: "bar",
				field: 0,
				opacity: 0
			}, {
        type: "line",
				field: "value",
        errorLowField: "lo",
        errorHighField: "hi",
        errorBars: {color: color, line: { width: 3 }},
        opacity: 0,
				color: color,
        markers: {
          visible: true,
          background: color,
          size: 10
        },
        
			tooltip: {
				visible: true,
        background: color,
				template: "#= category #: #= value.toPrecision(2)#%"
			}
			},{
				type: "rangeArea",
				fromField: "lo",
				toField: "hi",
				opacity: 0,
        color: color,
				tooltip: {
					visible: true,
          background: color,
				format: "{0}",
				template: "95% uncertainty interval (#= category #): #= tb_format_pct(value.from) #–#= tb_format_pct(value.to) #%"
				}
			}
              ],
			valueAxis: {
				labels: {
					format: "{0}"
				},
				title: {
					text: "Treatment coverage (%)"
				},
				line: {
					visible: false
				},
        min: 0,
			},
			categoryAxis: {
				field: "entity",
				labels: {
					rotation: "auto"
				},
				majorGridLines: {
					visible: true
				}
			}

		});
}

function createFig_3_3_2(fig_ID, data, color, title) {
   
		$(fig_ID).kendoChart({
			dataSource: data,
			chartArea: {
				height: 900
			},	
			title: {
				text: title,
				color: "black",
				font: "bold 16px  Arial,Helvetica,sans-serif",
        align: "left"
			},	
			legend: {
				position: "bottom"
			},
			series: [{
        type: "bar",
				field: 0,
				opacity: 0
			}, {
        type: "line",
				field: "c_cdr",
        errorLowField: "c_cdr_lo",
        errorHighField: "c_cdr_hi",
        errorBars: {color: color, line: { width: 3 }},
        opacity: 0,
				color: color,
        markers: {
          visible: true,
          background: color,
          size: 10
        },
        
			tooltip: {
				visible: true,
        background: color,
				template: "#= category #: #= value.toPrecision(2)#%"
			}
			},{
				type: "rangeArea",
				fromField: "c_cdr_lo",
				toField: "c_cdr_hi",
				opacity: 0,
        color: color,
				tooltip: {
					visible: true,
          background: color,
				format: "{0}",
				template: "95% uncertainty interval (#= category #): #= tb_format_pct(value.from) #–#= tb_format_pct(value.to) #%"
				}
			}
              ],
			valueAxis: {
				labels: {
					format: "{0}"
				},
				title: {
					text: "Treatment coverage (%)"
				},
				line: {
					visible: false
				},
        min: 0,
			},
			categoryAxis: {
				field: "entity",
				labels: {
					rotation: "auto"
				},
				majorGridLines: {
					visible: true
				}
			}

		});
}

function createFig_3_3_4(fig_ID, data) {
    
		$(fig_ID).kendoChart({
			dataSource: data,
			chartArea: {
				height: 500
			},	
			legend: {
				position: "bottom"
			},
      series: [{
				type: "line",
				field: "e_inc_tbhiv_num",
				color: "#ED1D24",
        markers: {
//				visible: false,
          size: 3
        },
				tooltip: {
					visible: true,
					format: "{0}",
					template: "Incident cases of TB among people living with HIV (#= category #): #= tb_format_thou(value) #"
				}
			},{
				type: "rangeArea",
				fromField: "e_inc_tbhiv_num_lo",
				toField: "e_inc_tbhiv_num_hi",
				color: "#ED1D24",
				tooltip: {
					visible: true,
				format: "{0}",
				template: "95% uncertainty interval (#= category #): #= tb_format_thou(value.from) #–#= tb_format_thou(value.to) #"
				}
			},{
				type: "line",
				field: "hivpos",
				color: "black",		
        markers: {
//				visible: false,
          size: 3
        },
				tooltip: {
					visible: true,
					format: "{0}",
					template: "Number of people notified with a new or relapse episode of TB who were known to be HIV-positive (#= category #): #= num_spacer(value) #"
				}
			},{
				type: "line",
				field: "art",
				color: "#277abe",		
        markers: {
//				visible: false,
          size: 3
        },
				tooltip: {
					visible: true,
					format: "{0}",
					template: "Number of TB patients who were started on antiretroviral therapy (#= category #): #= num_spacer(value) #"
				}
			},],
			valueAxis: {
				labels: {
          template: "#= axis_spacer(value/1e6) #"
				},
				title: {
					text: "New and relapse cases per year (millions)",
					visible: true
				},
				line: {
					visible: false
				}
			},
			categoryAxis: {
				field: "year",
				labels: {
					rotation: "auto",
          step: 3
				},
				majorGridLines: {
					visible: false
				},
				title: {
					text: "Year",
					visible: true
				}
			}

		});
}

function createFig_3_3_6(fig_ID, data) {
		$(fig_ID).kendoChart({
			dataSource: data,
			chartArea: {
				height: 500
			},	
			legend: {
				position: "bottom"
			},
			seriesDefaults: {
				type: "bar",
        stack: {
          type: "100%"
        },
        gap: 0.2
			},
			series: [{
        name: "Treatment success",
				field: "succ",
				color: "#009E73",
        tooltip: {
				visible: true,
				template: "Treatment success (#= category #): #= value.toPrecision(2) #%"
			}
			},{
        name: "Failure",
				field: "fail",
				color: "#ED1D24",
        tooltip: {
				visible: true,
				template: "Failure (#= category #): #= value.toPrecision(2) #%"
			}
			},{
        name: "Died",
				field: "died",
				color: "#F7941E",
        tooltip: {
				visible: true,
				template: "Died (#= category #): #= value.toPrecision(2) #%"
			}
			},{
        name: "Lost to follow-up",
				field: "ltfu",
				color: "#E5DDB3",
        tooltip: {
				visible: true,
				template: "Lost to follow-up (#= category #): #= value.toPrecision(2) #%"
			}
			},{
        name: "Not evaluated",
				field: "neval",
				color: "#D1D3D4",
        tooltip: {
				visible: true,
				template: "Not evaluated (#= category #): #= value.toPrecision(2) #%"
			}
			},
              ],
			valueAxis: {

				title: {
					text: "Percent of cohort"
				},
				line: {
					visible: false
				},
			},
			categoryAxis: {
				field: "entity",
				labels: {
					rotation: "auto"
				},
				majorGridLines: {
					visible: false
				}			}
		});
}

function createFig_3_3_7(fig_ID, data, filter, x_axis_title = True, legend_label = True, height) {
      
  	// Filter the dataset on the country variable
		dataJSON = data.filter( element => element.subgroup == filter);
  
		$(fig_ID).kendoChart({
			dataSource: dataJSON,
			chartArea: {
				height: height
			},	
      title: {
				text: filter,
				color: "black",
				font: "bold 14px  Arial,Helvetica,sans-serif",
        align: "center"
			},	
			legend: {
				position: "bottom",
        visible: legend_label
			},
			seriesDefaults: {
				type: "bar",
        stack: {
          type: "100%"
        },
        gap: 0.2
			},
			series: [{
        name: "Treatment success",
				field: "succ",
				color: "#009E73",
        tooltip: {
				visible: true,
				template: "Treatment success (#= category #): #= value.toPrecision(2) #%"
			}
			},{
        name: "Failure",
				field: "fail",
				color: "#ED1D24",
        tooltip: {
				visible: true,
				template: "Failure (#= category #): #= value.toPrecision(2) #%"
			}
			},{
        name: "Died",
				field: "died",
				color: "#F7941E",
        tooltip: {
				visible: true,
				template: "Died (#= category #): #= value.toPrecision(2) #%"
			}
			},{
        name: "Lost to follow-up",
				field: "ltfu",
				color: "#E5DDB3",
        tooltip: {
				visible: true,
				template: "Lost to follow-up (#= category #): #= value.toPrecision(2) #%"
			}
			},{
        name: "Not evaluated",
				field: "neval",
				color: "#D1D3D4",
        tooltip: {
				visible: true,
				template: "Not evaluated (#= category #): #= value.toPrecision(2) #%"
			}
			},
              ],
			valueAxis: {
				title: {
					text: "Percent of cohort",
          visible: x_axis_title
				},
				line: {
					visible: false
				},
        min: 0,
        max: 1
			},
			categoryAxis: {
				field: "year",
				labels: {
					rotation: "auto"
				},
				majorGridLines: {
					visible: false
				}			}
		});
}

function createFig_3_3_9(fig_ID, data) {
		$(fig_ID).kendoChart({
			dataSource: data,
			chartArea: {
				height: 500
			},	
			legend: {
				position: "bottom",
				visible: false,
			},
			seriesDefaults: {
				type: "bar",
        gap: 0.2
			},
			series: [{
        name: "Treatment success",
				field: "c_tsr_014",
				color: "#009E73",
        tooltip: {
				visible: true,
				template: "Treatment success (#= category #): #= value.toPrecision(2) #%"
			}
			}
              ],
			valueAxis: {

				title: {
					text: "Percent of cohort"
				},
				line: {
					visible: false
				},
				min: 0,
        max: 100
			},
			categoryAxis: {
				field: "entity",
				labels: {
					rotation: "auto"
				},
				majorGridLines: {
					visible: false
				}			}
		});
}

```


```{js, echo=FALSE}

/* Create the figures after the document has been loaded */

$(document).ready(function () {
  createFig_3_3_1("#fig_3_3_1",fig_3_3_1_data,"Darkgreen");
  createFig_3_3_2("#fig_3_3_2a",fig_3_3_2a_data,"dodgerblue","Children aged 0\u201314 years");
  createFig_3_3_2("#fig_3_3_2b",fig_3_3_2b_data,"goldenrod","Adults aged \u226515 years");
  createFig_3_3_4("#fig_3_3_4",fig_3_3_4_data);
  createFig_3_3_1("#fig_3_3_5",fig_3_3_5_data,"#ed6476");
  createFig_3_3_6("#fig_3_3_6",fig_3_3_6_data);
  createFig_3_3_7("#fig_3_3_7a",fig_3_3_7_data,"New and relapse TB cases",false,false,300);
  createFig_3_3_7("#fig_3_3_7b",fig_3_3_7_data,"New and relapse HIV-positive TB cases",true,true,370);
  createFig_3_3_6("#fig_3_3_8",fig_3_3_8_data);
  createFig_3_3_9("#fig_3_3_9",fig_3_3_9_data);

 }); 
 
```
