---
title: "Section 3.4 Drug-resistant TB: treatment and treatment coverage"
author: "Takuya Yamanaka"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
      out_dir <- "./html_drafts";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})
output: 
  html_fragment:
    # Don’t include a table of contents
    toc: no
    # Set standard figure width to 12 inches
    fig_width: 12
    # Don’t write figure captions
    fig_caption: FALSE
    # to save intermediate .png
    keep_md: true
    # Don't embed external resources (stylesheets, JS libraries) in the output 
    self_contained: FALSE

# To run this file and store output as html:
# rmarkdown::render(here::here("report/ch3-4.rmd"), output_file = "ch3-4.html", output_dir = here::here("report/html_drafts/"))
---


```{r setup, include=FALSE}
# Set chunk options.
# Results "asis" is useful to output markdown from a function
# Suppress messages, warnings and also the ## at the beginning of printed text

knitr::opts_chunk$set(echo = FALSE, 
                      results = "asis",
                      message = FALSE,
                      warning = FALSE,
                      error = TRUE)  # TEMP error=TRUE for debugging!

# Kill any attempt at using factors, unless we explicitly want them!
options(stringsAsFactors=FALSE)

# Load output packages ----
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
library(gtbreport)

library(jsonlite)
library(dplyr)
library(here)

# Get the data sets and computed values/statistics for section 3.4 ----
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
source(here('report/ch3-4_prepare_data.r'))

```


```{css, echo=FALSE}

/* Styles to make it easier to see in the html_fragment; this CSS can be included in the CSS widget of Sitefinity */
  
.red, .red a {
  color: #F21905; /* red text to show figure number */
}

```
<!-- Add links to stylesheets, JQuery and Kendo UI  -->

<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.301/styles/kendo.common.min.css" />
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.301/styles/kendo.default.min.css" />
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.301/styles/kendo.default.mobile.min.css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<script src="https://kendo.cdn.telerik.com/2022.1.301/js/jquery.min.js"></script>
<script src="https://kendo.cdn.telerik.com/2022.1.301/js/kendo.all.min.js"></script>
<script src="https://docs.telerik.com/kendo-ui/assets/bootstrap.min.js"></script>
<!-- End of links section -->


# 3.4 Drug-resistant TB treatment  

_Draft! Prepared `r Sys.Date()` using country-reported data CSV files dated `r csv_datestamp` `r if(show_estimates){paste0('and estimates files dated ', csv_estimate_datestamp)}`_


### <span class="red">Fig. 3.4.1</span> The global number of people reported to have been enrolled on treatment for MDR/RR-TB, 2015&#8211;`r report_year-1`

<div id="fig_3_4_1"></div>


### <span class="red">Fig. 3.4.2</span> Number of people diagnosed with MDR/RR-TB<span style="color:#277abe;"> (blue)</span> and enrolled on MDR-TB treatment<span style="color:red;"> (red)</span>, 2010&#8211;`r report_year-1`, 30 high MDR-TB burden countries

<div class="row">
<div class="col-md-4">
<div id="fig_3_4_2_AGO"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_AZE"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_BGD"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_3_4_2_BLR"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_CHN"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_PRK"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_3_4_2_COD"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_IND"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_IDN"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_3_4_2_KAZ"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_KGZ"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_MNG"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_3_4_2_MOZ"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_MMR"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_NPL"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_3_4_2_NGA"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_PAK"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_PNG"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_3_4_2_PER"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_PHL"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_MDA"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_3_4_2_RUS"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_SOM"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_ZAF"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_3_4_2_TJK"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_UKR"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_UZB"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_3_4_2_VNM"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_ZMB"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_2_ZWE"></div>
</div>
</div>


### <span class="red">Fig. 3.4.3</span> Global progress in the number of people treated for MDR/RR-TB between 2018 and `r report_year-1`, compared with cumulative targets set for 2018&#8211;2022 at the UN high-level meeting on TB

<span class="red">**!static figure!**</span>



### <span class="red">Fig. 3.4.4</span> Number of people diagnosed with MDR/RR-TB<span style="color:#277abe;"> (blue)</span> and number enrolled on MDR/RR-TB treatment<span style="color:red;"> (red)</span>, compared with estimates of the number of incident cases of MDR/RR-TB (95% uncertainty interval shown in <span style="color:`r gtbreport::palette_gtb("inc")`">green</span>), 2015&#8211;`r report_year-1`, globally and for WHO regions  

<div id="fig_3_4_4_global"></div>

<div class="row">
<div class="col-md-4">
<div id="fig_3_4_4_afro"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_4_amro"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_4_searo"></div>
</div>
</div>

<div class="row">
<div class="col-md-4">
<div id="fig_3_4_4_euro"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_4_emro"></div>
</div>
<div class="col-md-4">
<div id="fig_3_4_4_wpro"></div>
</div>
</div>



### <span class="red">Fig. 3.4.5</span> Estimated treatment coverage for MDR/RR-TB^a^ in `r report_year-1`, 30 high MDR-TB burden countries,^b^ WHO regions and globally

<div id="fig_3_4_5"></div>


### <span class="red">Fig. 3.4.6</span> The ten countries with the largest gaps between the number of people started on treatment for MDR-TB and the best estimates of MDR/RR-TB incidence,^a^ `r report_year-1`

<span class="red">**!static figure!**</span>


### <span class="red">Fig. 3.4.7</span> Treatment outcomes for people diagnosed with MDR/RR-TB globally, 2012&#8211;`r report_year-3` 

<div id="fig_3_4_7"></div>


### <span class="red">Fig. 3.4.8</span> Treatment outcomes for people diagnosed with MDR/RR-TB who were started on treatment in `r report_year-3`, WHO regions and globally  

<div id="fig_3_4_8"></div>


### <span class="red">Fig. 3.4.9</span> Countries that used bedaquiline for the treatment of MDR, pre-XDR-TB, and XDR-TB as part of expanded access, compassionate use or under normal programmatic conditions by the end of `r report_year-1`

<span class="red">**!static figure!**</span>


### <span class="red">Fig. 3.4.10</span> Countries that used all-oral longer MDR-TB treatment regimens by the end of `r report_year-1`

<span class="red">**!static figure!**</span>



### <span class="red">Fig. 3.4.11</span> Countries that used all-oral shorter MDR-TB treatment regimens by the end of `r report_year-1`

<span class="red">**!static figure!**</span>


### <span class="red">Fig. 3.4.12</span> Number of patients with active follow up of adverse events as a proportion of patients enrolled on treatment for drug-resistant TB, `r report_year-1`

<span class="red">**!static figure!**</span>


<script type="text/javascript">
/* JSON data objects for the figures */

var fig_3_4_1_data = `r f3.4.1_data %>% pivot_wider(names_from = age_group, values_from = how_many) %>% rename(age_014=3, age_15plus=4) %>% toJSON("rows")`   ;  

var fig_3_4_2_data = `r f3.4.2_data %>% select(country, year, rr_detected, rr_treated) %>% toJSON("rows")`   ;  

var fig_3_4_4_data = `r f3.4.4_data %>% toJSON("rows")`   ;  

var fig_3_4_5_data = `r f3.4.5_data %>% rename(value = c_rr_coverage , lo = c_rr_coverage_lo, hi = c_rr_coverage_hi) %>% toJSON("rows")`   ;  

var fig_3_4_7_data = `r f3.4.7_data %>% pivot_wider(names_from = outcome, values_from = value) %>% arrange(rev(year)) %>% rename(entity = 1, succ=3, fail=4, died=5, ltfu=6, neval=7) %>% toJSON("rows")`   ;  

var fig_3_4_8_data = `r f3.4.8_data %>% pivot_wider(names_from = outcome, values_from = value) %>% rename(succ=2, fail=3, died=4, ltfu=5, neval=6) %>% toJSON("rows")`   ;  
</script>

  
```{js, echo=FALSE}

function num_spacer(number) {
  // Change thousands separator to a non-breaking space as per WHO standard in tool tips
  return kendo.toString(number, 'n0').replace(/,/g, '&nbsp;')
}

/* format a number as thousands using GTB rounding rules */
function tb_format_thou(n) { 
  nt = n/1000; 
  if (nt < 100) {
    ntform = Number(nt.toPrecision(2))*1000;
      } else {
    ntform = Number(nt.toPrecision(3))*1000;
  } 
  return num_spacer(ntform)
}

function tb_format_pct(n) { 
  // Show percentages to 2 sig figs if under 100%
  if (n < 99.5) {
    return Number(n.toPrecision(2))
      } else {
    return Number(n.toPrecision(3))
  } 
}

/* Functions to create the figures */


function createFig_3_4_1() {
		$("#fig_3_4_1").kendoChart({
			dataSource: fig_3_4_1_data,
			chartArea: {
				height: 500
			},	
			legend: {
				position: "bottom"
			},
			seriesDefaults: {
				type: "column",
        stack: true,
        gap: 0.2
			},
			series: [{
        name: "All ages",
				field: "all",
				color: "#A5D727",
        tooltip: {
				visible: true,
				template: "All ages (#= category #): #= kendo.toString(value, 'n0').replace(/,/g, ' ') #"
			}
			},{
        name: "Adults aged \u226515 years or age not reported",
				field: "age_15plus",
				color: "#009E73",
        tooltip: {
				visible: true,
				template: "Adults aged \u226515 years or age not reported (#= category #): #= kendo.toString(value, 'n0').replace(/,/g, ' ') #"
			}
			},{
        name: "Children aged 0\u201314 years",
				field: "age_014",
				color: "red",
        tooltip: {
				visible: true,
				template: "Children aged 0\u201314 years (#= category #): #= kendo.toString(value, 'n0').replace(/,/g, ' ') #"
			}
			},
              ],
			valueAxis: {
				labels: {
				template: "#= kendo.format('{0}',value/1000) #",
				},
				title: {
					text: "Thousands"
				},
				line: {
					visible: false
				},
			},
			categoryAxis: {
				field: "year",
				labels: {
					rotation: "auto"
				},
				majorGridLines: {
					visible: false
				}			}
		});
}

function createFig_3_4_2(fig_ID, data, filter) {
  
  		// Filter the dataset on the country variable
		dataJSON = data.filter( element => element.country == filter);
  
		$(fig_ID).kendoChart({
			dataSource: dataJSON,
			chartArea: {
				height: 250
			},	
      title: {
				text: filter,
				color: "black",
				font: "bold 14px  Arial,Helvetica,sans-serif"
			},	
			legend: {
				position: "bottom"
			},
      series: [{
				type: "line",
				field: "rr_detected",
				color: "#277abe",
        markers: {
          size: 3
        },
				tooltip: {
					visible: true,
					format: "{0}",
					template: "Diagnosed with MDR/RR-TB (#= category #): #= kendo.toString(value, 'n0').replace(/,/g, ' ') #"
				}
			},{
				type: "line",
				field: "rr_treated",
				color: "red",  
        markers: {
          size: 3
        },
				tooltip: {
					visible: true,
					format: "{0}",
					template: "Enrolled on MDR-TB treatment (#= category #): #= kendo.toString(value, 'n0').replace(/,/g, ' ') #"
				}
			}],
			valueAxis: {
				labels: {
					template: "#= kendo.toString(value, 'n0').replace(/,/g, ' ') #"
				},
				title: {
					text: "Number of cases"
				},
				line: {
					visible: false
				}
			},
			categoryAxis: {
				field: "year",
				labels: {
					rotation: 0,
          step: 5
				},
				majorGridLines: {
					visible: false
				},
				title: {
					text: "Year"
				}
			}

		});
}

function createFig_3_4_4(fig_ID, data, filter) {
   	
  // Filter the dataset on the country variable
		dataJSON = data.filter( element => element.entity == filter);
   
		$(fig_ID).kendoChart({
			dataSource: dataJSON,
			chartArea: {
				height: 250
			},
      title: {
				text: filter,
				color: "black",
				font: "bold 14px  Arial,Helvetica,sans-serif",
        align: "center"
			},	
			legend: {
				position: "bottom"
			},
      series: [{
				type: "line",
				field: "e_inc_rr_num",
				color: "#91A93E",
        markers: {
          size: 3
        },
				tooltip: {
					visible: true,
					format: "{0}",
					template: "Estimates of the number of incident cases of MDR/RR-TB (#= category #): #= tb_format_thou(value) #"
				}
			},{
				type: "rangeArea",
				fromField: "e_inc_rr_num_lo",
				toField: "e_inc_rr_num_hi",
				color: "#91A93E",
				tooltip: {
					visible: true,
				format: "{0}",
				template: "95% uncertainty interval (#= category #): #= tb_format_thou(value.from) #–#= tb_format_thou(value.to) #"
				}
			},{
				type: "line",
				field: "rr_detected",
				color: "#277abe",		
        markers: {
          size: 3
        },
				tooltip: {
					visible: true,
					format: "{0}",
					template: "Number of people diagnosed with MDR/RR-TB (#= category #): #= kendo.toString(value, 'n0').replace(/,/g, ' ') #"
				}
			},{
				type: "line",
				field: "rr_treated",
				color: "Red",		
        markers: {
          size: 3
        },
				tooltip: {
					visible: true,
					format: "{0}",
					template: "Number enrolled on MDR-TB treatment (#= category #): #= kendo.toString(value, 'n0').replace(/,/g, ' ') #"
				}
			},],
			valueAxis: {
				labels: {
          template: "#= kendo.toString(value, 'n0').replace(/,/g, ' ') #"
				},
				title: {
					text: "Number per year"
				},
				line: {
					visible: false
				}
			},
			categoryAxis: {
				field: "year",
				labels: {
					rotation: 0,
          step: 3
				},
				majorGridLines: {
					visible: false
				},
				title: {
					text: "Year"
				}
			}

		});
}

function createFig_3_4_5(fig_ID, data, color) {
   
		$(fig_ID).kendoChart({
			dataSource: data,
			chartArea: {
				height: 900
			},	
			legend: {
				position: "bottom"
			},
			series: [{
        type: "bar",
				field: 0,
				opacity: 0
			}, {
        type: "line",
				field: "value",
        errorLowField: "lo",
        errorHighField: "hi",
        errorBars: {color: color, line: { width: 3 }},
        opacity: 0,
				color: color,
        markers: {
          visible: true,
          background: color,
          size: 10
        },
        
			tooltip: {
				visible: true,
        background: color,
				template: "#= category #: #= value.toPrecision(2)#%"
			}
			},{
				type: "rangeArea",
				fromField: "lo",
				toField: "hi",
				opacity: 0,
        color: color,
				tooltip: {
					visible: true,
          background: color,
				format: "{0}",
				template: "95% uncertainty interval (#= category #): #= tb_format_pct(value.from) #–#= tb_format_pct(value.to) #%"
				}
			}
              ],
			valueAxis: {
				labels: {
					format: "{0}"
				},
				title: {
					text: "Treatment coverage (%)"
				},
				line: {
					visible: false
				},
        min: 0,
			},
			categoryAxis: {
				field: "entity",
				labels: {
					rotation: "auto"
				},
				majorGridLines: {
					visible: true
				}
			}

		});
}

function createFig_3_4_7(fig_ID, data, y_axis_title_text) {
		$(fig_ID).kendoChart({
			dataSource: data,
			chartArea: {
				height: 500
			},	
			legend: {
				position: "bottom"
			},
			seriesDefaults: {
				type: "bar",
        stack: {
          type: "100%"
        },
        gap: 0.2
			},
			series: [{
        name: "Treatment success",
				field: "succ",
				color: "#009E73",
        tooltip: {
				visible: true,
				template: "Treatment success (#= category #): #= value.toPrecision(2) #%"
			}
			},{
        name: "Failure",
				field: "fail",
				color: "#ED1D24",
        tooltip: {
				visible: true,
				template: "Failure (#= category #): #= value.toPrecision(2) #%"
			}
			},{
        name: "Died",
				field: "died",
				color: "#F7941E",
        tooltip: {
				visible: true,
				template: "Died (#= category #): #= value.toPrecision(2) #%"
			}
			},{
        name: "Lost to follow-up",
				field: "ltfu",
				color: "#E5DDB3",
        tooltip: {
				visible: true,
				template: "Lost to follow-up (#= category #): #= value.toPrecision(2) #%"
			}
			},{
        name: "Not evaluated",
				field: "neval",
				color: "#D1D3D4",
        tooltip: {
				visible: true,
				template: "Not evaluated (#= category #): #= value.toPrecision(2) #%"
			}
			},
              ],
			valueAxis: {

				title: {
					text: "Percent of cohort"
				},
				line: {
					visible: false
				},
			},
			categoryAxis: {
				field: "entity",
				title: {
					text: y_axis_title_text
				},
				labels: {
					rotation: "auto"
				},
				majorGridLines: {
					visible: false
				}			}
		});
}
```

```{js, echo=FALSE}

/* Create the figures after the document has been loaded */

$(document).ready(function() {
  createFig_3_4_1();
    createFig_3_4_2("#fig_3_4_2_AGO",fig_3_4_2_data,"Angola");
                 createFig_3_4_2("#fig_3_4_2_PRK",fig_3_4_2_data,"Democratic People's Republic of Korea");
                 createFig_3_4_2("#fig_3_4_2_KGZ",fig_3_4_2_data,"Kyrgyzstan");
                 createFig_3_4_2("#fig_3_4_2_NGA",fig_3_4_2_data,"Nigeria");
                 createFig_3_4_2("#fig_3_4_2_MDA",fig_3_4_2_data,"Republic of Moldova");
                 createFig_3_4_2("#fig_3_4_2_UKR",fig_3_4_2_data,"Ukraine");
                 createFig_3_4_2("#fig_3_4_2_AZE",fig_3_4_2_data,"Azerbaijan");
                 createFig_3_4_2("#fig_3_4_2_COD",fig_3_4_2_data,"Democratic Republic of the Congo");
                 createFig_3_4_2("#fig_3_4_2_MNG",fig_3_4_2_data,"Mongolia");
                 createFig_3_4_2("#fig_3_4_2_PAK",fig_3_4_2_data,"Pakistan");
                 createFig_3_4_2("#fig_3_4_2_RUS",fig_3_4_2_data,"Russian Federation");
                 createFig_3_4_2("#fig_3_4_2_UZB",fig_3_4_2_data,"Uzbekistan");
                 createFig_3_4_2("#fig_3_4_2_BGD",fig_3_4_2_data,"Bangladesh");
                 createFig_3_4_2("#fig_3_4_2_IND",fig_3_4_2_data,"India");
                 createFig_3_4_2("#fig_3_4_2_MOZ",fig_3_4_2_data,"Mozambique");
                 createFig_3_4_2("#fig_3_4_2_PNG",fig_3_4_2_data,"Papua New Guinea");
                 createFig_3_4_2("#fig_3_4_2_SOM",fig_3_4_2_data,"Somalia");
                 createFig_3_4_2("#fig_3_4_2_VNM",fig_3_4_2_data,"Viet Nam");
                 createFig_3_4_2("#fig_3_4_2_BLR",fig_3_4_2_data,"Belarus");
                 createFig_3_4_2("#fig_3_4_2_IDN",fig_3_4_2_data,"Indonesia");
                 createFig_3_4_2("#fig_3_4_2_MMR",fig_3_4_2_data,"Myanmar");
                 createFig_3_4_2("#fig_3_4_2_PER",fig_3_4_2_data,"Peru");
                 createFig_3_4_2("#fig_3_4_2_ZAF",fig_3_4_2_data,"South Africa");
                 createFig_3_4_2("#fig_3_4_2_ZMB",fig_3_4_2_data,"Zambia");
                 createFig_3_4_2("#fig_3_4_2_CHN",fig_3_4_2_data,"China");
                 createFig_3_4_2("#fig_3_4_2_KAZ",fig_3_4_2_data,"Kazakhstan");
                 createFig_3_4_2("#fig_3_4_2_NPL",fig_3_4_2_data,"Nepal");
                 createFig_3_4_2("#fig_3_4_2_PHL",fig_3_4_2_data,"Philippines");
                 createFig_3_4_2("#fig_3_4_2_TJK",fig_3_4_2_data,"Tajikistan");
                 createFig_3_4_2("#fig_3_4_2_ZWE",fig_3_4_2_data,"Zimbabwe");
                 createFig_3_4_4("#fig_3_4_4_global",fig_3_4_4_data,"Global");
                 createFig_3_4_4("#fig_3_4_4_euro",fig_3_4_4_data,"European Region");
                 createFig_3_4_4("#fig_3_4_4_afro",fig_3_4_4_data,"African Region");
                 createFig_3_4_4("#fig_3_4_4_emro",fig_3_4_4_data,"Eastern Mediterranean Region");
                 createFig_3_4_4("#fig_3_4_4_amro",fig_3_4_4_data,"Region of the Americas");
                 createFig_3_4_4("#fig_3_4_4_wpro",fig_3_4_4_data,"Western Pacific Region");
                 createFig_3_4_4("#fig_3_4_4_searo",fig_3_4_4_data,"South-East Asia Region");
                 createFig_3_4_5("#fig_3_4_5",fig_3_4_5_data,"Darkblue");
                 createFig_3_4_7("#fig_3_4_7",fig_3_4_7_data,"Year started on treatment");
                 createFig_3_4_7("#fig_3_4_8",fig_3_4_8_data,"");



});

```
