---
title: "Chapter 6.3"
author: "Takuya Yamanaka" # Based on the test version of Chapter 5 "chapter_5_test" by Hazim 
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
      out_dir <- "./html_drafts";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})
output: 
  html_fragment:
    # Don’t include a table of contents
    toc: no
    # Set standard figure width to 12 inches
    fig_width: 12
    # Don’t write figure captions
    fig_caption: FALSE
    # to save intermediate .png
    keep_md: true 
    # Don't embed external resources (stylesheets, JS libraries) in the output 
    self_contained: FALSE   
---

```{r setup, include=FALSE}


# Set chunk options.
# Results "asis" is needed to avoid xtable output being html encoded
# Suppress messages, warnings and also the ## at the beginning of printed text
# Set a default figure width too.

knitr::opts_chunk$set(echo = FALSE,
                      results = "asis",
                      message = FALSE,
                      warning = FALSE,
                      fig.width = 12)


# Load output packages ----
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
library(ggplot2)
library(dplyr)
library(scales)
library(RColorBrewer)
library(whomap)
library(gtbreport)
library(here)
library(cowplot)

library(jsonlite)
library(dplyr)
library(here)
# Get the data sets and computed values/statistics for section 6.3 ----
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
source(here('report/ch6-3_prepare_data.r'))

```
  
```{css, echo=FALSE}

/* Styles to make it easier to see in the html_fragment; this CSS can be included in the CSS widget of Sitefinity */
  
.red, .red a {
  color: #F21905; /* red text to show figure number */
}

```

<!-- Add links to stylesheets, JQuery and Kendo UI  -->

<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.301/styles/kendo.common.min.css" />
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.301/styles/kendo.default.min.css" />
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.301/styles/kendo.default.mobile.min.css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<script src="https://kendo.cdn.telerik.com/2022.1.301/js/jquery.min.js"></script>
<script src="https://kendo.cdn.telerik.com/2022.1.301/js/kendo.all.min.js"></script>
<script src="https://docs.telerik.com/kendo-ui/assets/bootstrap.min.js"></script>
<!-- End of links section -->

# 6.3 TB determinants  

_Draft! Prepared `r Sys.Date()` using country-reported data CSV files dated `r csv_datestamp` `r if(show_estimates){paste0('and estimates files dated ', csv_estimate_datestamp)}`_


### <span style="color:#F21905">Fig. 6.3.1</span> The relationship between GDP per capita and the prevalence of undernourishment, and TB incidence per 100 000 population, `r report_year-1`^a^

<span class="red">**!static figure!**</span>


### <span style="color:#F21905">Fig. 6.3.2</span> Global estimates of the number of incident TB cases attributable to selected risk factors, `r report_year-1`


<span class="red">**!Impossible to have different colors for errorbar and maker by category!**</span>
<div id="fig_6_3_2"></div>
  
 

### <span style="color:#F21905">Fig. 6.3.3</span> Estimated number of incident TB cases attributable to five risk factors at country level, `r report_year-1`
#### (a) Undernourishment 
<span class="red">**!static figure!**</span>

#### (b) Alcohol use disorders 
<span class="red">**!static figure!**</span>

#### (c) HIV infection
<span class="red">**!static figure!**</span>

#### (d) Diabetes  
<span class="red">**!static figure!**</span>

#### (e) Smoking  
<span class="red">**!static figure!**</span>
  


### <span style="color:#F21905">Fig. 6.3.4</span> Estimated number of TB cases attributable to five risk factors, 30 high TB burden countries and 3 global TB watchlist countries,^a^ `r report_year - 1` 
 

<div class="row">
<div class="col-md-4">
<div id="fig_6_3_4_AGO"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_BGD"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_BRA"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_4_KHM"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_CAF"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_CHN"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_4_COG"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_PRK"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_COD"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_4_ETH"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_GAB"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_IND"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_4_IDN"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_KEN"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_LSO"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_4_LBR"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_MNG"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_MOZ"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_4_MMR"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_NAM"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_NGA"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_4_PAK"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_PNG"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_PHL"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_4_RUS"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_SLE"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_ZAF"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_4_THA"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_UGA"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_TZA"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_4_VNM"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_ZMB"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_4_ZWE"></div>
</div>
</div>



### <span style="color:#F21905">Fig. 6.3.5</span> Status of selected SDG indicators beyond SDG 3 at country level, latest available year
#### (a) Access to clean fuels
<span class="red">**!static figure!**</span>

#### (b) Income inequality
<span class="red">**!static figure!**</span>

#### (c) Living in poverty
<span class="red">**!static figure!**</span>

#### (d) Access to social protection
<span class="red">**!static figure!**</span>

#### (e) Living in slums
<span class="red">**!static figure!**</span>

#### (f) Undernourishment
<span class="red">**!static figure!**</span>



### <span style="color:#F21905">Fig. 6.3.6</span> Status of selected SDG indicators beyond SDG 3 in 30 high TB burden and 3 global TB watchlist countries, latest available year


<span class="red">**!Cannot find a function to have color gradient by value for a circular bar chart!**</span><BR>
<span class="red">**!As an alternative, suggest using a radar chart for interactive chart!**</span>
 

<div class="row">
<div class="col-md-4">
<div id="fig_6_3_6_v2_AGO"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_BGD"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_BRA"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_6_v2_KHM"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_CAF"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_CHN"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_6_v2_COG"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_PRK"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_COD"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_6_v2_ETH"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_GAB"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_IND"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_6_v2_IDN"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_KEN"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_LSO"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_6_v2_LBR"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_MNG"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_MOZ"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_6_v2_MMR"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_NAM"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_NGA"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_6_v2_PAK"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_PNG"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_PHL"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_6_v2_RUS"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_SLE"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_ZAF"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_6_v2_THA"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_UGA"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_TZA"></div>
</div>
</div>
<div class="row">
<div class="col-md-4">
<div id="fig_6_3_6_v2_VNM"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_ZMB"></div>
</div>
<div class="col-md-4">
<div id="fig_6_3_6_v2_ZWE"></div>
</div>
</div>

<script type="text/javascript">
/* JSON data objects for the figures */

var fig_6_3_2_data = `r f6.3.2_data %>% select(risk_factor,best,lo,hi) %>% mutate(color = c("dodgerblue","deeppink","goldenrod","firebrick","green")) %>% arrange(desc(best)) %>% toJSON("rows")`   ;

var fig_6_3_4_data = `r f6.3.4_data %>% select(country,risk_factor,riskgrp,best,lo,hi) %>% mutate(color = ifelse(riskgrp=="alc","#084EA2",ifelse(riskgrp=="dia","#0491D1",ifelse(riskgrp=="hiv","#ED1D24",ifelse(riskgrp=="smk","#B92270","#91A93E"))))) %>% add_row(country = c("Angola","Central African Republic","Gabon","Uganda"), risk_factor = "Smoking") %>% add_row(country = c("Uganda","Zambia","Zimbabwe"), risk_factor = "Undernourishment")  %>% add_row(country = c("Uganda"), risk_factor = "Alcohol use disorders")  %>% add_row(country = c("Uganda"), risk_factor = "Diabetes") %>% arrange(factor(risk_factor, levels = c("Alcohol use disorders","Diabetes","HIV","Smoking","Undernourishment"), ordered = TRUE)) %>% toJSON("rows")`   ;

var fig_6_3_6_data = `r f6.3.6_data %>% mutate(country = ifelse(iso3=='PRK',"Democratic People's Republic of Korea",country)) %>%  mutate(country = ifelse(iso3=='COD',"Democratic Republic of the Congo",country)) %>% mutate(sdg = ifelse(sdg == "Income equality", "Income\nequality",sdg)) %>% add_column(color = rep(brewer.pal(6, "Paired"), 33))  %>% toJSON("rows")`   ;

</script>


```{js, echo=FALSE}

/* Functions to create the figures */

/* Functions to organize number with thousands separator */
function num_spacer(number) {
  // Change thousands separator to a non-breaking space as per WHO standard
      if (number >= 10 | number==0) {
        return kendo.toString(number, 'n0').replace(/,/g, '&nbsp;');
      } else if (number<10 & number>=1) {
      return kendo.toString(number, 'n1').replace(/,/g, '&nbsp;');
      } else {
      return kendo.toString(number, 'n2').replace(/,/g, '&nbsp;');
      }
}

function axis_spacer(number) {
  // Change thousands separator to a non-breaking space as per WHO standard
      if (number >= 10 | number == 0 ) {
        return kendo.toString(number, 'n0').replace(/,/g, ' ');
      } else {return kendo.toString(number, 'n1').replace(/,/g, ' ');
             }
}

/* format a number as thousands using GTB rounding rules */
function tb_format_thou(n) { 
  nt = n/1000; 
  if (nt < 100) {
    ntform = Number(nt.toPrecision(2))*1000;
      } else {
    ntform = Number(nt.toPrecision(3))*1000;
  } 
  return num_spacer(ntform)
}


/* Functions to create the figures */

function createFig_6_3_2(fig_ID, data) {
   
		$(fig_ID).kendoChart({
			dataSource: data,
			chartArea: {
				height: 400
			},	
			legend: {
				position: "bottom"
			},
			series: [{
        type: "bar",
				field: 0,
				opacity: 0
			}, {
        type: "line",
				field: "best",
        errorLowField: "lo",
        errorHighField: "hi",
        errorBars: {color: "grey", line: { width: 2 }},
				color: "color",
        markers: {
          visible: true,
          background: "grey",
          size: 15
        },
        
			tooltip: {
				visible: true,
				template: "#= category #: #= num_spacer(value/1e6) # million"
			}
			},{
				type: "rangeArea",
				fromField: "lo",
				toField: "hi",
				opacity: 0,
        color: "color",
				tooltip: {
					visible: true,
          background: "color",
				format: "{0}",
				template: "95% uncertainty interval (#= category #): #= num_spacer(value.from/1e6) #–#= num_spacer(value.to/1e6) #"
				}
			}
              ],
			valueAxis: {
				labels: {
					template: "#= axis_spacer(value/1e6) #"
				},
				title: {
					text: "Number of cases (millions)"
				},
				line: {
					visible: false
				},
        min: 0,
			},
			categoryAxis: {
				field: "risk_factor",
				labels: {
					rotation: "auto"
				},
				majorGridLines: {
					visible: true
				}
			}

		});
}



function createFig_6_3_4(fig_ID, data, filter) {
  	
  // Filter the dataset on the country variable
		dataJSON = data.filter( element => element.country == filter);
  
		$(fig_ID).kendoChart({
			dataSource: dataJSON,
			chartArea: {
				height: 250
			},	
			legend: {
				position: "bottom"
			},
			title: {
				text: filter,
				color: "black",
				font: "bold 14px  Arial,Helvetica,sans-serif",
				align: "center"
			},	
			series: [{
        type: "bar",
        field: "best",
		gap: 0.3,
        errorLowField: "lo",
        errorHighField: "hi",
        errorBars: {color: "black", line: { width: 1 }},
				color: "color",     
			tooltip: {
				visible: true,
				template: "#= category #: #= num_spacer(value/1e3) # thousand"
			}
      }, {
				type: "rangeArea",
				fromField: "lo",
				toField: "hi",
				opacity: 0,
        color: "color",
				tooltip: {
					visible: true,
				format: "{0}",
				template: "95% uncertainty interval (#= category #): #= num_spacer(value.from/1e3) #–#= num_spacer(value.to/1e3) #"
				}
			}
              ],
			valueAxis: {
				labels: {
					template: "#= axis_spacer(value/1e3) #"
				},
				title: {
					text: "Cases (thousands)"
				},
				line: {
					visible: false
				},
        min: 0,
			},
			categoryAxis: {
				field: "risk_factor",
				labels: {
					rotation: "auto"
				},
				majorGridLines: {
					visible: true
				}
			}

		});
}

function createFig_6_3_6(fig_ID, data, filter) {
  	
  // Filter the dataset on the country variable
		dataJSON = data.filter( element => element.country == filter);
  
		$(fig_ID).kendoChart({
			dataSource: dataJSON,
			chartArea: {
				height: 250
			},	
			legend: {
				position: "bottom"
			},
			title: {
				text: filter,
				color: "black",
				font: "bold 14px  Arial,Helvetica,sans-serif",
				align: "center"
			},	
			series: [{
        type: "radarColumn",
        field: "value",
				  color: function(e) {
            var colors =  ["#A6CEE3","#1F78B4","#B2DF8A","#33A02C","#FB9A99","#E31A1C"];
            var index = e.index % colors.length;
            return colors[index];   
          },    
			tooltip: {
				visible: true,
				template: "#= category #: #= kendo.toString(value, 'n0')#"
			}
      },
              ],
			valueAxis: {
				labels: {
					template: "#= kendo.toString(value, 'n0') #"
				},
				line: {
					visible: false
				},
        min: 0,
        max: 100,
        majorUnit: 25,
			},
			categoryAxis: {
				field: "sdg",
				labels: {
					rotation: "auto"
				},
				majorGridLines: {
					visible: true
				}
			}

		});
}

function createFig_6_3_6_v2(fig_ID, data, filter) {
  	
  // Filter the dataset on the country variable
		dataJSON = data.filter( element => element.country == filter);
  
		$(fig_ID).kendoChart({
			dataSource: dataJSON,
			chartArea: {
				height: 250
			},	
			legend: {
				position: "bottom"
			},
			title: {
				text: filter,
				color: "black",
				font: "bold 14px  Arial,Helvetica,sans-serif",
				align: "center"
			},	
			series: [{
        type: "radarLine",
        field: "value",
        color: "dodgerblue",
           markers: {
             visible: true,
             size: 5
           },
			tooltip: {
				visible: true,
				template: "#= category #: #= kendo.toString(value, 'n0')#"
			}
      },
              ],
			valueAxis: {
				labels: {
					template: "#= kendo.toString(value, 'n0') #"
				},
				line: {
					visible: false
				},
        min: 0,
        max: 100,
        majorUnit: 25,
			},
			categoryAxis: {
				field: "sdg",
				labels: {
					rotation: "auto"
				},
				majorGridLines: {
					visible: true
				}
			}

		});
}

```

```{js, echo=FALSE}

/* Create the figures after the document has been loaded */

$(document).ready(function () {
  createFig_6_3_2("#fig_6_3_2",fig_6_3_2_data);
  createFig_6_3_4("#fig_6_3_4_AGO",fig_6_3_4_data,"Angola");
  createFig_6_3_4("#fig_6_3_4_COG",fig_6_3_4_data,"Congo");
  createFig_6_3_4("#fig_6_3_4_IND",fig_6_3_4_data,"India");
  createFig_6_3_4("#fig_6_3_4_MNG",fig_6_3_4_data,"Mongolia");
  createFig_6_3_4("#fig_6_3_4_PAK",fig_6_3_4_data,"Pakistan");
  createFig_6_3_4("#fig_6_3_4_THA",fig_6_3_4_data,"Thailand");
  createFig_6_3_4("#fig_6_3_4_BGD",fig_6_3_4_data,"Bangladesh");
  createFig_6_3_4("#fig_6_3_4_PRK",fig_6_3_4_data,"Democratic People's Republic of Korea");
  createFig_6_3_4("#fig_6_3_4_IDN",fig_6_3_4_data,"Indonesia");
  createFig_6_3_4("#fig_6_3_4_MOZ",fig_6_3_4_data,"Mozambique");
  createFig_6_3_4("#fig_6_3_4_PNG",fig_6_3_4_data,"Papua New Guinea");
  createFig_6_3_4("#fig_6_3_4_UGA",fig_6_3_4_data,"Uganda");
  createFig_6_3_4("#fig_6_3_4_BRA",fig_6_3_4_data,"Brazil");
  createFig_6_3_4("#fig_6_3_4_COD",fig_6_3_4_data,"Democratic Republic of the Congo");
  createFig_6_3_4("#fig_6_3_4_KEN",fig_6_3_4_data,"Kenya");
  createFig_6_3_4("#fig_6_3_4_MMR",fig_6_3_4_data,"Myanmar");
  createFig_6_3_4("#fig_6_3_4_PHL",fig_6_3_4_data,"Philippines");
  createFig_6_3_4("#fig_6_3_4_TZA",fig_6_3_4_data,"United Republic of Tanzania");
  createFig_6_3_4("#fig_6_3_4_CAF",fig_6_3_4_data,"Central African Republic");
  createFig_6_3_4("#fig_6_3_4_ETH",fig_6_3_4_data,"Ethiopia");
  createFig_6_3_4("#fig_6_3_4_LSO",fig_6_3_4_data,"Lesotho");
  createFig_6_3_4("#fig_6_3_4_NAM",fig_6_3_4_data,"Namibia");
  createFig_6_3_4("#fig_6_3_4_SLE",fig_6_3_4_data,"Sierra Leone");
  createFig_6_3_4("#fig_6_3_4_VNM",fig_6_3_4_data,"Viet Nam");
  createFig_6_3_4("#fig_6_3_4_CHN",fig_6_3_4_data,"China");
  createFig_6_3_4("#fig_6_3_4_GAB",fig_6_3_4_data,"Gabon");
  createFig_6_3_4("#fig_6_3_4_LBR",fig_6_3_4_data,"Liberia");
  createFig_6_3_4("#fig_6_3_4_NGA",fig_6_3_4_data,"Nigeria");
  createFig_6_3_4("#fig_6_3_4_ZAF",fig_6_3_4_data,"South Africa");
  createFig_6_3_4("#fig_6_3_4_ZMB",fig_6_3_4_data,"Zambia");
  createFig_6_3_4("#fig_6_3_4_ZWE",fig_6_3_4_data,"Zimbabwe");
  createFig_6_3_4("#fig_6_3_4_RUS",fig_6_3_4_data,"Russian Federation");
  createFig_6_3_4("#fig_6_3_4_KHM",fig_6_3_4_data,"Cambodia");
  
  createFig_6_3_6_v2("#fig_6_3_6_v2_AGO",fig_6_3_6_data,"Angola");
  createFig_6_3_6_v2("#fig_6_3_6_v2_COG",fig_6_3_6_data,"Congo");
  createFig_6_3_6_v2("#fig_6_3_6_v2_IND",fig_6_3_6_data,"India");
  createFig_6_3_6_v2("#fig_6_3_6_v2_MNG",fig_6_3_6_data,"Mongolia");
  createFig_6_3_6_v2("#fig_6_3_6_v2_PAK",fig_6_3_6_data,"Pakistan");
  createFig_6_3_6_v2("#fig_6_3_6_v2_THA",fig_6_3_6_data,"Thailand");
  createFig_6_3_6_v2("#fig_6_3_6_v2_BGD",fig_6_3_6_data,"Bangladesh");
  createFig_6_3_6_v2("#fig_6_3_6_v2_PRK",fig_6_3_6_data,"Democratic People's Republic of Korea");
  createFig_6_3_6_v2("#fig_6_3_6_v2_IDN",fig_6_3_6_data,"Indonesia");
  createFig_6_3_6_v2("#fig_6_3_6_v2_MOZ",fig_6_3_6_data,"Mozambique");
  createFig_6_3_6_v2("#fig_6_3_6_v2_PNG",fig_6_3_6_data,"Papua New Guinea");
  createFig_6_3_6_v2("#fig_6_3_6_v2_UGA",fig_6_3_6_data,"Uganda");
  createFig_6_3_6_v2("#fig_6_3_6_v2_BRA",fig_6_3_6_data,"Brazil");
  createFig_6_3_6_v2("#fig_6_3_6_v2_COD",fig_6_3_6_data,"Democratic Republic of the Congo");
  createFig_6_3_6_v2("#fig_6_3_6_v2_KEN",fig_6_3_6_data,"Kenya");
  createFig_6_3_6_v2("#fig_6_3_6_v2_MMR",fig_6_3_6_data,"Myanmar");
  createFig_6_3_6_v2("#fig_6_3_6_v2_PHL",fig_6_3_6_data,"Philippines");
  createFig_6_3_6_v2("#fig_6_3_6_v2_TZA",fig_6_3_6_data,"United Republic of Tanzania");
  createFig_6_3_6_v2("#fig_6_3_6_v2_CAF",fig_6_3_6_data,"Central African Republic");
  createFig_6_3_6_v2("#fig_6_3_6_v2_ETH",fig_6_3_6_data,"Ethiopia");
  createFig_6_3_6_v2("#fig_6_3_6_v2_LSO",fig_6_3_6_data,"Lesotho");
  createFig_6_3_6_v2("#fig_6_3_6_v2_NAM",fig_6_3_6_data,"Namibia");
  createFig_6_3_6_v2("#fig_6_3_6_v2_SLE",fig_6_3_6_data,"Sierra Leone");
  createFig_6_3_6_v2("#fig_6_3_6_v2_VNM",fig_6_3_6_data,"Viet Nam");
  createFig_6_3_6_v2("#fig_6_3_6_v2_CHN",fig_6_3_6_data,"China");
  createFig_6_3_6_v2("#fig_6_3_6_v2_GAB",fig_6_3_6_data,"Gabon");
  createFig_6_3_6_v2("#fig_6_3_6_v2_LBR",fig_6_3_6_data,"Liberia");
  createFig_6_3_6_v2("#fig_6_3_6_v2_NGA",fig_6_3_6_data,"Nigeria");
  createFig_6_3_6_v2("#fig_6_3_6_v2_ZAF",fig_6_3_6_data,"South Africa");
  createFig_6_3_6_v2("#fig_6_3_6_v2_ZMB",fig_6_3_6_data,"Zambia");
  createFig_6_3_6_v2("#fig_6_3_6_v2_ZWE",fig_6_3_6_data,"Zimbabwe");
  createFig_6_3_6_v2("#fig_6_3_6_v2_RUS",fig_6_3_6_data,"Russian Federation");
  createFig_6_3_6_v2("#fig_6_3_6_v2_KHM",fig_6_3_6_data,"Cambodia");


 });  


```
