---
title: "Featured topics: MAF-TB"
author: "Takuya Yamanaka"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) {
  out_dir <- "./html_drafts";
  rmarkdown::render(inputFile,
                    encoding=encoding,
                    output_dir=file.path(dirname(inputFile), out_dir))})
output: 
  html_fragment:
    # Don’t include a table of contents
    toc: no
    # Set standard figure width to 12 inches
    fig_width: 12
    # Don’t write figure captions
    fig_caption: FALSE
    keep_md: true
    # Don't embed external resources (stylesheets, JS libraries) in the output 
    self_contained: FALSE
    
---
```{r, echo=FALSE, warning=FALSE, message=FALSE}


# Set chunk options.
# Results "asis" is useful to output markdown from a function
# Suppress messages, warnings and also the ## at the beginning of printed text
knitr::opts_chunk$set(echo = FALSE, 
                      results = "asis",
                      message = FALSE,
                      warning = FALSE)

# Set up the running environment ----
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#source("io/set_environment.r")  # particular to each person so this file is in the ignore list
# Load packages ----
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
library(dplyr)
library(tidyr)
library(here)
library(stringr)
library(jsonlite)

# Load TB data ----
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
maf1 <- read.csv(here("./csv/maf_fig1.csv"))
maf2 <- read.csv(here("./csv/maf_fig2.csv"))
maf3 <- read.csv(here("./csv/maf_fig3.csv"))

```


```{css, echo=FALSE}

/* Styles to make it easier to see in the html_fragment; this CSS can be included in the CSS widget of Sitefinity */
  
.red, .red a {
  color: #F21905; /* red text to show figure number */
}

```

<!-- Add links to stylesheets, JQuery and Kendo UI  -->

<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.301/styles/kendo.common.min.css" />
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.301/styles/kendo.default.min.css" />
<link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.301/styles/kendo.default.mobile.min.css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<script src="https://kendo.cdn.telerik.com/2022.1.301/js/jquery.min.js"></script>
<script src="https://kendo.cdn.telerik.com/2022.1.301/js/kendo.all.min.js"></script>
<script src="https://docs.telerik.com/kendo-ui/assets/bootstrap.min.js"></script>
<!-- End of links section -->

### <span class="fig" style="color:#F21905">Fig. 1.</span> Trends in the public availability of annual national TB reports from 2020 to 2022 (%)

<div id="fig_MAF_1"></div>

<BR>

### <span class="fig" style="color:#F21905">Fig. 2.</span> Trends in the set-up or strengthening of national multisectoral and multistakeholder accountability and review mechanisms under high-level leadership, as available from 2020 to 2022 (%)

<div id="fig_MAF_2"></div>

<BR>


### <span class="fig" style="color:#F21905">Fig. 3.</span> Reported trends in the engagement of civil society and affected communities in the multisectoral accountability and review mechanism from 2020 to 2022 (%)

<div id="fig_MAF_3"></div>

<BR>


<script type="text/javascript">
/* JSON data objects for the figures */

var fig_MAF_1_data = `r maf1 %>% mutate(year=factor(year, labels=c(2020,2021,2022))) %>% select(!cat2) %>% pivot_wider(names_from = year,values_from = value) %>% rename(pct2020=2,pct2021=3,pct2022=4) %>% mutate(cat=str_wrap(cat, width = 24,indent = 2)) %>% toJSON("rows") `   ;  

var fig_MAF_2_data = `r maf2 %>% mutate(year=factor(year, labels=c(2020,2021,2022))) %>% select(!cat2) %>% pivot_wider(names_from = year,values_from = value) %>% rename(pct2020=2,pct2021=3,pct2022=4) %>% mutate(cat=str_wrap(cat, width = 24,indent = 2)) %>% toJSON("rows") ` 

var fig_MAF_3_data = `r maf3 %>% mutate(year=factor(year, labels=c(2020,2021,2022))) %>% select(!cat2) %>% pivot_wider(names_from = year,values_from = value) %>% rename(pct2020=2,pct2021=3,pct2022=4) %>% mutate(cat=str_wrap(cat, width = 24,indent = 2)) %>% toJSON("rows") ` 


</script>


```{js, echo=FALSE}

/* Functions to create the figures */

/* Functions to organize number with thousands separator */

function num_spacer(number) {
  // Change thousands separator to a non-breaking space as per WHO standard
      if (number >= 10 | number==0) {
        return kendo.toString(number, 'n0').replace(/,/g, '&nbsp;');
      } else if (number<10 & number>=1) {
      return kendo.toString(number, 'n1').replace(/,/g, '&nbsp;');
      } else {
      return kendo.toString(number, 'n2').replace(/,/g, '&nbsp;');
      }
}

function axis_spacer(number) {
  // Change thousands separator to a non-breaking space as per WHO standard
      if (number >= 10 | number == 0 ) {
        return kendo.toString(number, 'n0').replace(/,/g, ' ');
      } else {return kendo.toString(number, 'n1').replace(/,/g, ' ');
             }
}

/* format a number as thousands using GTB rounding rules */
function tb_format_thou(n) { 
  nt = n/1000; 
  if (nt < 100) {
    ntform = Number(nt.toPrecision(2))*1000;
      } else {
    ntform = Number(nt.toPrecision(3))*1000;
  } 
  return num_spacer(ntform)
}


function tb_format_pct(n) { 
  // Show percentages to 2 sig figs if under 100%
  if (n < 99.5) {
    return n.toPrecision(2)
      } else {
    return n.toPrecision(3)
  } 
}

function tb_format_num(n) { 
  // Show percentages to 2 sig figs if under 100%
  if (n < 100) {
    return Number(n.toPrecision(2))
      } else {
    return kendo.toString(n, 'n0').replace(/,/g, ' ');
  } 
}

function createFig_MAF(fig_ID,data) {
		$(fig_ID).kendoChart({
			dataSource: data,
			chartArea: {
				height: 500
			},	
			legend: {
				position: "bottom"
			},
			seriesDefaults: {
				type: "column",
        gap: 2,
        spacing: 0,
			},
			series: [{
        name: "2020",
				field: "pct2020",
				color: "#FC1C1E",
        tooltip: {
				visible: true,
				template: "#= category # (2020): #= Number(value.toPrecision(2)) #%"
			}
			},{
        name: "2021",
				field: "pct2021",
				color: "#00a76d",
        tooltip: {
				visible: true,
				template: "#= category # (2021): #= Number(value.toPrecision(2)) #%"
			}
			},{
        name: "2022",
				field: "pct2022",
				color: "#0091D1",
        tooltip: {
				visible: true,
				template: "#= category # (2022): #= Number(value.toPrecision(2)) #%"
			}
			}, ],
			valueAxis: {
				labels: {
				template: "#= kendo.format('{0}',value) #",
				},
				title: {
					text: "Percentage"
				},
				line: {
					visible: false
				},
        min: 0,
        max: 100
			},
			categoryAxis: {
				field: "cat",
				labels: {
					rotation: 0
				},
				majorGridLines: {
					visible: false
				}			}
		});
}



```

```{js, echo=FALSE}

/* Create the figures after the document has been loaded */
$(document).ready(function() {
  createFig_MAF("#fig_MAF_1",fig_MAF_1_data);
  createFig_MAF("#fig_MAF_2",fig_MAF_2_data);
  createFig_MAF("#fig_MAF_3",fig_MAF_3_data);
  
});

```
